### ISSUE TITLE
uninstall enhancement

### ISSUE THREAD

**Issue by hostbbb** [AsyncWeb/bigbluebutton-streaming#20]
uninstall currently just reverts the html5 client to original.  The actual process still run on server.

Should 

1) stop pm2 process
2) remove the docker image
3) remove any needed packages.

**Comment by nishekh-e-r** [comment]
@hostbbb  Thanks for pointing out currently I am currently working on these.

**Comment by nishekh-e-r** [comment]
@hostbbb Thanks for testing and sharing your feedback on uninstall script. we have updated uninstall.sh script. Please let us know if you encounter any other problems or have more feedback.
