### ISSUE TITLE
Live Streaming is not working

### ISSUE THREAD

**Issue by gmath2** [AsyncWeb/bigbluebutton-streaming#31]
Hello
I hope you are well
For me, even though I followed the instructions (and the video) exactly, it installs the live streaming on my server (2.6.10 and 2.7) but when I'm in the session after entering my live streaming server details (youtube) and pressing start Streaming gives me black screen and stops streaming.
I have installed several times on a clean BBB server, but always the same behavior. Every time I reinstall Ubuntu and reinstall BBB from scratch.
I'm not an IT guy and can't look it up myself. I just follow your instructions. If you want help me.
Thank you very much

**Comment by gmath2** [comment]
Θα εγκαταστήσω ακόμα μια φορά και θα σας πω.
Και πάλι ευχαριστώ.

**Comment by gmath2** [comment]
> Θα εγκαταστήσω άλλη μια φορά και θα σας ενημερώσω. Ευχαριστώ και πάλι.

Again the same: It doesn't work.
Please......

**Comment by gmath2** [comment]
I will install one more time and let you know.
Thanks again.

**Comment by gmath2** [comment]
Again the same: It doesn't work.
Please......

**Comment by magnaapps** [comment]
F12 shows me the following error when i start the Streamer

![image](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/47348430/a0f1c74d-5b61-4dc5-a81b-a57043415c31)

**Comment by gmath2** [comment]
> @gmath2, I recommend the following steps to diagnose the issue you're experiencing.
> 
> 1. Ensure the pm2 is present and running the node application on your BigBluebutton server. To check this, use the command `pm2 list`.
>    ![pm2-list](https://user-images.githubusercontent.com/87962465/257797649-8b1577a5-58ad-42fe-be28-5c3995f7479c.png)
>    If the `bbb-streaming` is listed and its status is anything other than `online`, you should restart the `bbb-streaming` by using the following command:
>    `pm2 restart bbb-streaming`
>    ![Screenshot from 2023-08-02 17-02-47](https://user-images.githubusercontent.com/87962465/257800256-c0ee5bee-4af4-4882-8bde-6152c915a15a.png)
> 2. Furthermore, it's important to note under which user account you're running the install script. We don't advise executing the install script as a `root` or `bigbluebutton` user. Instead, please create a new user with sudo access and execute the install command with this user.
> 
> I hope this helps, and feel free to reach out if you require more assistance.

**Comment by gmath2** [comment]
> 1. pm2 restart bbb-streaming
Ευχαριστώ για την απάντηση!!
![Εικόνα1](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/60414762/0956d651-2a4b-407e-963e-63306af59a3c)

**Comment by gmath2** [comment]
> @gmath2, συνιστώ τα ακόλουθα βήματα για τη διάγνωση του προβλήματος που αντιμετωπίζετε.
> 
> 1. Βεβαιωθείτε ότι το pm2 είναι παρόν και εκτελεί την εφαρμογή κόμβου στον διακομιστή BigBluebutton. Για να το ελέγξετε, χρησιμοποιήστε την εντολή `pm2 list`.
>    ![pm2-list](https://user-images.githubusercontent.com/87962465/257797649-8b1577a5-58ad-42fe-be28-5c3995f7479c.png)
>    Εάν `bbb-streaming`εμφανίζεται στη λίστα και η κατάστασή του είναι κάτι διαφορετικό από το `online`, θα πρέπει να το επανεκκινήσετε `bbb-streaming`χρησιμοποιώντας την ακόλουθη εντολή:
>    `pm2 restart bbb-streaming`
>    ![Στιγμιότυπο από 2023-08-02 17-02-47](https://user-images.githubusercontent.com/87962465/257800256-c0ee5bee-4af4-4882-8bde-6152c915a15a.png)
> 2. Επιπλέον, είναι σημαντικό να σημειώσετε σε ποιον λογαριασμό χρήστη εκτελείτε το σενάριο εγκατάστασης. Δεν συμβουλεύουμε την εκτέλεση του σεναρίου εγκατάστασης ως χρήστης `root`ή `bigbluebutton`χρήστη. Αντίθετα, δημιουργήστε έναν νέο χρήστη με πρόσβαση sudo και εκτελέστε την εντολή εγκατάστασης με αυτόν τον χρήστη.
> 
> Ελπίζω ότι αυτό βοηθά και μη διστάσετε να απευθυνθείτε αν χρειάζεστε περισσότερη βοήθεια.

Thanks for the reply, but the same thing happens, even though it shows online.
I'm not installing as root, but as gmath, as shown:
![Εικόνα1](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/60414762/c2d63434-611c-4dfd-90af-cf07bbf021fc)
I only noticed that during installation it said:
> preinstall
> npx npm-force-resolutions
Need to install the following packages:
   npm-force-resolutions@0.0.10
Ok to proceed? (y)
I pressed y + enter
and continue the installation. If this is the fault, I don't know how to fix it

**Comment by gmath2** [comment]
> @gmath2, I recommend the following steps to diagnose the issue you're experiencing.
> 
> 1. Ensure the pm2 is present and running the node application on your BigBluebutton server. To check this, use the command `pm2 list`.
>    ![pm2-list](https://user-images.githubusercontent.com/87962465/257797649-8b1577a5-58ad-42fe-be28-5c3995f7479c.png)
>    If the `bbb-streaming` is listed and its status is anything other than `online`, you should restart the `bbb-streaming` by using the following command:
>    `pm2 restart bbb-streaming`
>    ![Screenshot from 2023-08-02 17-02-47](https://user-images.githubusercontent.com/87962465/257800256-c0ee5bee-4af4-4882-8bde-6152c915a15a.png)
> 2. Furthermore, it's important to note under which user account you're running the install script. We don't advise executing the install script as a `root` or `bigbluebutton` user. Instead, please create a new user with sudo access and execute the install command with this user.
> 
> I hope this helps, and feel free to reach out if you require more assistance.

Thanks for the reply, but the same thing happens, even though it shows online.
![image](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/60414762/0b00bc29-316f-47aa-a072-6e46a46a1a96)
I'm not installing as root, but as gmath, as shown:
preinstall
npx npm-force-resolutions
Need to install the following packages:
npm-force-resolutions@0.0.10
Ok to proceed? (y)
I pressed y + enter
and continue the installation. If this is the fault, I don't know how to fix it

**Comment by gmath2** [comment]
> @gmath2, I recommend the following steps to diagnose the issue you're experiencing.
> 
> 1. Ensure the pm2 is present and running the node application on your BigBluebutton server. To check this, use the command `pm2 list`.
>    ![pm2-list](https://user-images.githubusercontent.com/87962465/257797649-8b1577a5-58ad-42fe-be28-5c3995f7479c.png)
>    If the `bbb-streaming` is listed and its status is anything other than `online`, you should restart the `bbb-streaming` by using the following command:
>    `pm2 restart bbb-streaming`
>    ![Screenshot from 2023-08-02 17-02-47](https://user-images.githubusercontent.com/87962465/257800256-c0ee5bee-4af4-4882-8bde-6152c915a15a.png)
> 2. Furthermore, it's important to note under which user account you're running the install script. We don't advise executing the install script as a `root` or `bigbluebutton` user. Instead, please create a new user with sudo access and execute the install command with this user.
> 
> I hope this helps, and feel free to reach out if you require more assistance.

Thanks for the reply, but the same thing happens, even though it shows online.
![image](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/60414762/5d0770f7-c263-4ebf-857d-c828e9250873)

I'm not installing as root, but as gmath, as shown:
preinstall
npx npm-force-resolutions
Need to install the following packages:
npm-force-resolutions@0.0.10
Ok to proceed? (y)
I pressed y + enter
and continue the installation. If this is the fault, I don't know how to fix it

**Comment by nishekh-e-r** [comment]
@gmath2 I will be happy to help you please write to `support@higheredlab.com`, to schedule a call.

**Comment by nishekh-e-r** [comment]
@gmath2 

Run this command `pm2 logs bbb-streaming` 
```
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```
The error in your log file indicates that the backend `bbb-streaming` requires `sudo` access. To resolve this, you can configure `sudo` to not ask for a password for the relevant user. Here's how:


1. Open a terminal.
2. Type `sudo visudo`. This will open the sudoers file in the system's default text editor. The visudo command checks the syntax of the sudoers file to help prevent you from accidentally locking yourself out of the system.

3. Scroll down to the section of the file that looks like this:

```bash
# User privilege specification
root    ALL=(ALL:ALL) ALL
```

4. Underneath the root user, add the following line, replacing `username` with the username for which you want to allow passwordless sudo commands:

```bash
username ALL=(ALL:ALL) NOPASSWD: ALL
```

5. Press `Ctrl+X` to exit the editor, then `Y` to save changes, and `Enter` to confirm.

Now, the user you added will be able to use `sudo` without being asked for a password. 

and restart bbb-streaming `pm2 restart bbb-streaming`

Please try it and let us know.

**Comment by gmath2** [comment]
> @gmath2
> 
> Run this command `pm2 logs bbb-streaming`
> 
> ```
> 0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> 0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> 0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> 0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> 0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> 0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> ```
> 
> The error in your log file indicates that the backend `bbb-streaming` requires `sudo` access. To resolve this, you can configure `sudo` to not ask for a password for the relevant user. Here's how:
> 
> 1. Open a terminal.
> 2. Type `sudo visudo`. This will open the sudoers file in the system's default text editor. The visudo command checks the syntax of the sudoers file to help prevent you from accidentally locking yourself out of the system.
> 3. Scroll down to the section of the file that looks like this:
> 
> ```shell
> # User privilege specification
> root    ALL=(ALL:ALL) ALL
> ```
> 
> 4. Underneath the root user, add the following line, replacing `username` with the username for which you want to allow passwordless sudo commands:
> 
> ```shell
> username ALL=(ALL:ALL) NOPASSWD: ALL
> ```
> 
> 5. Press `Ctrl+X` to exit the editor, then `Y` to save changes, and `Enter` to confirm.
> 
> Now, the user you added will be able to use `sudo` without being asked for a password.
> 
> and restart bbb-streaming `pm2 restart bbb-streaming`
> 
> Please try it and let us know.

Thank you very much
It worked!!!!!
The secret was in NOPASSWD: ALL
If you want the instructions you gave me include them in the README.
One more question: When BBB is upgraded, will Live Streaming still work? Now however if I update BBB to version 2.7.0-beta.3 the streaming stops working, and it can't be installed because it requires 2.7.0-beta.2. Are you planning to make it work once it's installed, still work in subsequent BBB upgrades?
However, the app now works perfectly!!!
Thank you once again. I'll be looking forward to her development so that she works in future versions of BBB as well.
Really on BBB 2.6.11, can it be installed?
Thanks again, and for taking the time to help me. Be well always
gmath

**Comment by nishekh-e-r** [comment]
we will try to upgrade to other versions also.
