### ISSUE TITLE
Dev Tools error on start meeting

### ISSUE THREAD

**Issue by magnaapps** [AsyncWeb/bigbluebutton-streaming#34]
I have tried both versions but the meeting shows a Blank Blue background and not streaming when you start the streamer with following error below. 

![image](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/47348430/2b9c458c-eba2-4c7f-a7fd-d0bafed42cea)

**Comment by nishekh-e-r** [comment]
@magnaapps can you try to troubleshoot as mentioned here
[https://github.com/AsyncWeb/bigbluebutton-streaming#%EF%B8%8F-troubleshooting](https://github.com/AsyncWeb/bigbluebutton-streaming#%EF%B8%8F-troubleshooting)
If you face any other issues please post here

**Comment by magnaapps** [comment]
pm2 logs bbb-streaming

0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
![image](https://github.com/AsyncWeb/bigbluebutton-streaming/assets/47348430/5ecd8af6-e56b-459c-b6b4-f8e9283b1380)

**Comment by nishekh-e-r** [comment]
@magnaapps 
0|bbb-stre | sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

The error in your log file indicates that the backend `bbb-streaming` requires `sudo` access. To resolve this, you can configure `sudo` to not ask for a password for the relevant user. Here's how:


1. Open a terminal.
2. Type `sudo visudo`. This will open the sudoers file in the system's default text editor. The visudo command checks the syntax of the sudoers file to help prevent you from accidentally locking yourself out of the system.

3. Scroll down to the section of the file that looks like this:

```bash
# User privilege specification
root    ALL=(ALL:ALL) ALL
```

4. Underneath the root user, add the following line, replacing `username` with the username for which you want to allow passwordless sudo commands:

```bash
username ALL=(ALL:ALL) NOPASSWD: ALL
```

5. Press `Ctrl+X` to exit the editor, then `Y` to save changes, and `Enter` to confirm.

Now, the user you added will be able to use `sudo` without being asked for a password.

**Comment by magnaapps** [comment]
Thank works, I think making sure username ALL=(ALL:ALL) NOPASSWD: ALL is setup before start is important
